import { initGame, drawCard, placeCard } from './packages/game-engine/src/engine';
import { CharacterCard } from './packages/game-engine/src/types';
import fs from 'fs';

// Load the seed data generated by the subagent
const seedData = JSON.parse(fs.readFileSync('./packages/game-engine/src/seed.json', 'utf-8'));
const cardPool = seedData.slice(0, 10) as CharacterCard[];

console.log("🎮 --- ANIME ARENA ENGINE TEST --- 🎮\n");

// 1. Initialize Game
let state = initGame(cardPool);
console.log(`✅ Game Initialized. Current Phase: ${state.phase}, Current Player: ${state.currentPlayer}`);

// 2. Player 1 Draws
state = drawCard(state);
console.log(`\n🃏 Player 1 Drew a Card!`);
console.log(`   Face-Up Character: ${state.cardPool?.name} (Universe: ${state.cardPool?.universe})`);
console.log(`   New Phase: ${state.phase}`);

// 3. Player 1 Places Card in Captain Slot (Index 0)
state = placeCard(state, 1, 0);
const p1Captain = state.players[1].team[0];
console.log(`\n⚔️  Player 1 placed ${p1Captain.card?.name} in the ${p1Captain.role} slot.`);
console.log(`   Player 1 Current Score: ${state.players[1].score}`);
console.log(`   Score Breakdown:`, state.players[1].scoreBreakdown);

// 4. Turn Advancements
console.log(`\n🔄 Turn Advanced! Next Phase: ${state.phase}, Current Player: ${state.currentPlayer}`);

console.log("\n✅ Engine State Machine is working flawlessly!");
